[project]
name = "jiraworklogs"
version = "0.2.0"
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "requests < 3.0",
]

[dependency-groups]
dev = [
    "pip-tools",    # provides pip-compile to update lockfile
]
test = [
    "pytest == 8.4.2",  # last version that supports Python 3.9
    "pytest-cov",
]


[project.scripts]
# Function that should be run when using the `jiraworklogs` command via CLI
jiraworklogs = "jiraworklogs.main:main"


[tool.pytest.ini_options]
pythonpath = ["src", "src/jiraworklogs"]
testpaths = ["test"]
